using System.ComponentModel.DataAnnotations;
using System.Data.Entity.ModelConfiguration;

namespace DbContextAutoGenerated.Models.Mapping
{
    public class EmployeeAlternateMap : EntityTypeConfiguration<EmployeeAlternate>
    {
        public EmployeeAlternateMap()
        {
            // Primary Key
            this.HasKey(t => t.Id);

            // Properties
            // Table & Column Mappings
            this.ToTable("EmployeeAlternates");
            this.Property(t => t.Id).HasColumnName("Id");
            this.Property(t => t.EmployeeId).HasColumnName("EmployeeId");
            this.Property(t => t.AlternateEmployeeId).HasColumnName("AlternateEmployeeId");
            this.Property(t => t.StartDate).HasColumnName("StartDate");
            this.Property(t => t.EndDate).HasColumnName("EndDate");
            this.Property(t => t.Notify).HasColumnName("Notify");
            this.Property(t => t.Unlimited).HasColumnName("Unlimited");
            this.Property(t => t.Enabled).HasColumnName("Enabled");

            // Relationships
            this.HasRequired(t => t.employee)
                .WithMany(t => t.EmployeeAlternates)
                .HasForeignKey(d => d.AlternateEmployeeId);
            this.HasRequired(t => t.employee1)
                .WithMany(t => t.EmployeeAlternates1)
                .HasForeignKey(d => d.EmployeeId);

        }
    }
}
