using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;

namespace DbContextAutoGenerated.Models.Mapping
{
    public class EmployeeAlternateMap : EntityTypeConfiguration<EmployeeAlternate>
    {
        public EmployeeAlternateMap()
        {
            // Primary Key
            this.HasKey(t => new { t.Id, t.EmployeeId, t.AlternateEmployeeId, t.Notify, t.Enabled });

            // Properties
            this.Property(t => t.Id)
                .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);

            this.Property(t => t.EmployeeId)
                .HasDatabaseGeneratedOption(DatabaseGeneratedOption.None);

            this.Property(t => t.AlternateEmployeeId)
                .HasDatabaseGeneratedOption(DatabaseGeneratedOption.None);

            // Table & Column Mappings
            this.ToTable("EmployeeAlternates");
            this.Property(t => t.Id).HasColumnName("Id");
            this.Property(t => t.EmployeeId).HasColumnName("EmployeeId");
            this.Property(t => t.AlternateEmployeeId).HasColumnName("AlternateEmployeeId");
            this.Property(t => t.StartDate).HasColumnName("StartDate");
            this.Property(t => t.EndDate).HasColumnName("EndDate");
            this.Property(t => t.Notify).HasColumnName("Notify");
            this.Property(t => t.Unlimited).HasColumnName("Unlimited");
            this.Property(t => t.Enabled).HasColumnName("Enabled");
        }
    }
}
