using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;

namespace DbContextAutoGenerated.Models.Mapping
{
    public class EmployeeAlternateMap : EntityTypeConfiguration<EmployeeAlternate>
    {
        public EmployeeAlternateMap()
        {
            // Primary Key
            this.HasKey(t => new { t.Id, t.EmployeeSid, t.AlternateEmployeeSid, t.Notify, t.Enabled });

            // Properties
            this.Property(t => t.Id)
                .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);

            this.Property(t => t.EmployeeSid)
                .IsRequired()
                .HasMaxLength(46);

            this.Property(t => t.AlternateEmployeeSid)
                .IsRequired()
                .HasMaxLength(46);

            // Table & Column Mappings
            this.ToTable("EmployeeAlternates");
            this.Property(t => t.Id).HasColumnName("Id");
            this.Property(t => t.EmployeeSid).HasColumnName("EmployeeSid");
            this.Property(t => t.AlternateEmployeeSid).HasColumnName("AlternateEmployeeSid");
            this.Property(t => t.StartDate).HasColumnName("StartDate");
            this.Property(t => t.EndDate).HasColumnName("EndDate");
            this.Property(t => t.Notify).HasColumnName("Notify");
            this.Property(t => t.Unlimited).HasColumnName("Unlimited");
            this.Property(t => t.Enabled).HasColumnName("Enabled");
        }
    }
}
