using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;

namespace DbContextAutoGenerated.Models.Mapping
{
    public class WfwExecutionEventMap : EntityTypeConfiguration<WfwExecutionEvent>
    {
        public WfwExecutionEventMap()
        {
            // Primary Key
            this.HasKey(t => t.Id);

            // Properties
            this.Property(t => t.CreaterSid)
                .IsRequired()
                .HasMaxLength(46);

            // Table & Column Mappings
            this.ToTable("WfwExecutionEvents");
            this.Property(t => t.Id).HasColumnName("Id");
            this.Property(t => t.WfwDocumentWorkStagesId).HasColumnName("WfwDocumentWorkStagesId");
            this.Property(t => t.Date).HasColumnName("Date");
            this.Property(t => t.CreaterSid).HasColumnName("CreaterSid");
            this.Property(t => t.RoleId).HasColumnName("RoleId");
            this.Property(t => t.AlternateId).HasColumnName("AlternateId");
            this.Property(t => t.ResultId).HasColumnName("ResultId");
            this.Property(t => t.Comment).HasColumnName("Comment");

            // Relationships
            this.HasRequired(t => t.WfwDocumentWorkStage)
                .WithMany(t => t.WfwExecutionEvents)
                .HasForeignKey(d => d.WfwDocumentWorkStagesId);
            this.HasRequired(t => t.WfwEventsResult)
                .WithMany(t => t.WfwExecutionEvents)
                .HasForeignKey(d => d.ResultId);

        }
    }
}
