using System;
using System.Collections.Generic;

namespace DbContextStuffAutoGenerated.Models
{
    public partial class C__RefactorLog
    {
        public System.Guid OperationKey { get; set; }
    }
}
