using System;
using System.Collections.Generic;

namespace DbContextStuffAutoGenerated.Models
{
    public partial class CaptureOutputLog
    {
        public int Id { get; set; }
        public string OutputText { get; set; }
    }
}
