using System;
using System.Collections.Generic;

namespace DbContextStuffAutoGenerated.Models
{
    public partial class employeeAlternate
    {
        public int Id { get; set; }
        public string EmployeeSid { get; set; }
        public string AlternateEmployeeSid { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool Notify { get; set; }
        public Nullable<bool> Unlimited { get; set; }
        public bool Enabled { get; set; }
    }
}
