using System;
using System.Collections.Generic;

namespace DbContextStuffAutoGenerated.Models
{
    public partial class position_import
    {
        public int id { get; set; }
        public string name_dat { get; set; }
        public string name_rod { get; set; }
    }
}
