using System;
using System.Collections.Generic;

namespace DbContextStuffAutoGenerated.Models
{
    public partial class request_history
    {
        public int Id { get; set; }
        public int RequestId { get; set; }
        public int RequestOldStatusId { get; set; }
        public int RequestNewStatusId { get; set; }
        public string CrteatorSid { get; set; }
        public System.DateTime Date { get; set; }
        public virtual employee employee { get; set; }
        public virtual request request { get; set; }
        public virtual request_statuses request_statuses { get; set; }
        public virtual request_statuses request_statuses1 { get; set; }
    }
}
