using System;
using System.Collections.Generic;

namespace DbContextStuffAutoGenerated.Models
{
    public partial class request_statuses
    {
        public request_statuses()
        {
            this.request_history = new List<request_history>();
            this.request_history1 = new List<request_history>();
            this.requests = new List<request>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool Enabled { get; set; }
        public virtual ICollection<request_history> request_history { get; set; }
        public virtual ICollection<request_history> request_history1 { get; set; }
        public virtual ICollection<request> requests { get; set; }
    }
}
