using System;
using System.Collections.Generic;

namespace DbContextStuffAutoGenerated.Models
{
    public partial class TestClass
    {
        public string Name { get; set; }
        public int SchemaId { get; set; }
    }
}
