using System;
using System.Collections.Generic;

namespace DbContextStuffAutoGenerated.Models
{
    public partial class wd_work_holidays
    {
        public System.DateTime date { get; set; }
    }
}
