using System;
using System.Collections.Generic;

namespace DbContextStuffAutoGenerated.Models
{
    public partial class work_hours
    {
        public int id_time { get; set; }
        public System.TimeSpan time { get; set; }
        public string sys_name { get; set; }
    }
}
