CREATE TABLE [dbo].[organizations] (
    [id]                   INT            IDENTITY (1, 1) NOT NULL,
    [name]                 NVARCHAR (150) NOT NULL,
    [enabled]              BIT            DEFAULT ((1)) NOT NULL,
    [dattim1]              DATETIME       DEFAULT (getdate()) NOT NULL,
    [dattim2]              DATETIME       DEFAULT ('3.3.3333') NOT NULL,
    [display_in_list]      BIT            DEFAULT ((1)) NOT NULL,
    [full_name]            NVARCHAR (500) NULL,
    [order_num]            INT            DEFAULT ((500)) NOT NULL,
    [creator_sid]          VARCHAR (46)   NULL,
    [address_ur]           NVARCHAR (500) NULL,
    [address_fact]         NVARCHAR (500) NULL,
    [phone]                NVARCHAR (50)  NULL,
    [email]                NVARCHAR (50)  NULL,
    [inn]                  NVARCHAR (12)  NULL,
    [kpp]                  NVARCHAR (20)  NULL,
    [ogrn]                 NVARCHAR (20)  NULL,
    [rs]                   NVARCHAR (50)  NULL,
    [bank]                 NVARCHAR (500) NULL,
    [ks]                   NVARCHAR (50)  NULL,
    [bik]                  NVARCHAR (50)  NULL,
    [okpo]                 NVARCHAR (50)  NULL,
    [okved]                NVARCHAR (50)  NULL,
    [manager_name]         NVARCHAR (150) NULL,
    [manager_name_dat]     NVARCHAR (150) NULL,
    [manager_position]     NVARCHAR (250) NULL,
    [manager_position_dat] NVARCHAR (250) NULL,
    [site]                 NVARCHAR (50)  NULL,
    [director_sid]         VARCHAR (46)   NULL,
    [sys_name]             NVARCHAR (50)  NULL,
    [id_director]          INT            NULL,
    PRIMARY KEY CLUSTERED ([id] ASC)
);

