CREATE TABLE [dbo].[recruit_question_forms] (
    [id]                         INT             IDENTITY (1, 1) NOT NULL,
    [link_sid]                   VARCHAR (46)    NOT NULL,
    [id_selection]               INT             NOT NULL,
    [id_candidate]               INT             NOT NULL,
    [id_vacancy]                 INT             NOT NULL,
    [surname]                    NVARCHAR (50)   NULL,
    [name]                       NVARCHAR (50)   NULL,
    [patronymic]                 NVARCHAR (50)   NULL,
    [birth_date]                 DATE            NULL,
    [male]                       BIT             NULL,
    [display_name]               NVARCHAR (150)  NULL,
    [phone]                      NVARCHAR (50)   NULL,
    [email]                      NVARCHAR (150)  NULL,
    [nationality]                NVARCHAR (150)  NULL,
    [address]                    NVARCHAR (250)  NULL,
    [have_conviction]            BIT             NULL,
    [organization_owner]         BIT             NULL,
    [have_owned_organization]    NVARCHAR (500)  NULL,
    [id_question_when_work]      INT             NULL,
    [have_driver_license]        BIT             NULL,
    [have_car]                   BIT             NULL,
    [car_model]                  NVARCHAR (150)  NULL,
    [driver_expirence]           INT             NULL,
    [id_question_marital_status] INT             NULL,
    [id_position]                INT             NULL,
    [position_name]              NVARCHAR (250)  NULL,
    [minimum_salaty]             MONEY           NULL,
    [optimal_salary]             MONEY           NULL,
    [id_education]               INT             NULL,
    [science_degree]             NVARCHAR (500)  NULL,
    [computer_skills]            NVARCHAR (MAX)  NULL,
    [have_trip_limit]            BIT             NULL,
    [have_health_limit]          BIT             NULL,
    [free_time_rest]             NVARCHAR (4000) NULL,
    [life_attainment]            NVARCHAR (4000) NULL,
    [long_term_goal]             NVARCHAR (4000) NULL,
    [advantage]                  NVARCHAR (4000) NULL,
    [dattim1]                    DATETIME        CONSTRAINT [DF_recruit_question_forms_dattim1] DEFAULT (getdate()) NULL,
    [client_ip]                  NVARCHAR (50)   NULL,
    [client_user_agent]          NVARCHAR (250)  NULL,
    CONSTRAINT [PK_recruit_question_forms] PRIMARY KEY CLUSTERED ([id] ASC)
);

