using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;

namespace DbContextStuffAutoGenerated.Models.Mapping
{
    public class employeeAlternateMap : EntityTypeConfiguration<employeeAlternate>
    {
        public employeeAlternateMap()
        {
            // Primary Key
            this.HasKey(t => t.Id);

            // Properties
            this.Property(t => t.EmployeeSid)
                .IsRequired()
                .HasMaxLength(46);

            this.Property(t => t.AlternateEmployeeSid)
                .IsRequired()
                .HasMaxLength(46);

            // Table & Column Mappings
            this.ToTable("employeeAlternates");
            this.Property(t => t.Id).HasColumnName("Id");
            this.Property(t => t.EmployeeSid).HasColumnName("EmployeeSid");
            this.Property(t => t.AlternateEmployeeSid).HasColumnName("AlternateEmployeeSid");
            this.Property(t => t.StartDate).HasColumnName("StartDate");
            this.Property(t => t.EndDate).HasColumnName("EndDate");
            this.Property(t => t.Notify).HasColumnName("Notify");
            this.Property(t => t.Unlimited).HasColumnName("Unlimited");
            this.Property(t => t.Enabled).HasColumnName("Enabled");
        }
    }
}
