using System;
using System.Collections.Generic;

namespace DbContextAutoGenerated.Models
{
    public partial class DocumentType
    {
        public DocumentType()
        {
            this.Documents = new List<Document>();
        }

        public int Id { get; set; }
        public int SchemeId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool Enabled { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
        public virtual WfwScheme WfwScheme { get; set; }
    }
}
