using System;
using System.Collections.Generic;

namespace DbContextAutoGenerated.Models
{
    public partial class Document
    {
        public string Id { get; set; }
        public string LinkToDoc { get; set; }
        public string Name { get; set; }
        public int TypeId { get; set; }
        public Nullable<int> ExecutionId { get; set; }
        public bool Enabled { get; set; }
        public virtual WfwDocumentExecution WfwDocumentExecution { get; set; }
        public virtual DocumentType DocumentType { get; set; }
    }
}
