using System;
using System.Collections.Generic;

namespace DbContextAutoGenerated.Models
{
    public partial class EmployeeRole
    {
        public EmployeeRole()
        {
            this.WfwSchemeStages = new List<WfwSchemeStage>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int EmployeeId { get; set; }
        public bool Enabled { get; set; }
        public virtual employee employee { get; set; }
        public virtual ICollection<WfwSchemeStage> WfwSchemeStages { get; set; }
    }
}
