using System;
using System.Collections.Generic;

namespace DbContextAutoGenerated.Models
{
    public partial class EmployeeRole
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string EmployeeSid { get; set; }
        public bool Enabled { get; set; }
    }
}
