using System;
using System.Collections.Generic;

namespace DbContextAutoGenerated.Models
{
    public partial class EmployeeAlternate
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public int AlternateEmployeeId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool Notify { get; set; }
        public Nullable<bool> Unlimited { get; set; }
        public bool Enabled { get; set; }
    }
}
