using System;
using System.Collections.Generic;

namespace DbContextAutoGenerated.Models
{
    public partial class employee
    {
        public employee()
        {
            this.EmployeeAlternates = new List<EmployeeAlternate>();
            this.EmployeeAlternates1 = new List<EmployeeAlternate>();
            this.EmployeeRoles = new List<EmployeeRole>();
            this.WfwDocumentExecutions = new List<WfwDocumentExecution>();
            this.WfwExecutionEvents = new List<WfwExecutionEvent>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public bool Enabled { get; set; }
        public virtual ICollection<EmployeeAlternate> EmployeeAlternates { get; set; }
        public virtual ICollection<EmployeeAlternate> EmployeeAlternates1 { get; set; }
        public virtual ICollection<EmployeeRole> EmployeeRoles { get; set; }
        public virtual ICollection<WfwDocumentExecution> WfwDocumentExecutions { get; set; }
        public virtual ICollection<WfwExecutionEvent> WfwExecutionEvents { get; set; }
    }
}
