using System;
using System.Collections.Generic;

namespace DbContextAutoGenerated.Models
{
    public partial class WfwDocumentWorkStage
    {
        public WfwDocumentWorkStage()
        {
            this.WfwExecutionEvents = new List<WfwExecutionEvent>();
        }

        public int Id { get; set; }
        public int ExecutionId { get; set; }
        public int Level { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string CoordinatorSid { get; set; }
        public Nullable<System.DateTimeOffset> Date { get; set; }
        public Nullable<int> ResultId { get; set; }
        public string Comment { get; set; }
        public bool Enabled { get; set; }
        public virtual WfwDocumentExecution WfwDocumentExecution { get; set; }
        public virtual WfwEventsResult WfwEventsResult { get; set; }
        public virtual ICollection<WfwExecutionEvent> WfwExecutionEvents { get; set; }
    }
}
