using System;
using System.Collections.Generic;

namespace DbContextAutoGenerated.Models
{
    public partial class WfwDocumentExecution
    {
        public WfwDocumentExecution()
        {
            this.Documents = new List<Document>();
            this.WfwExecutionEvents = new List<WfwExecutionEvent>();
        }

        public int Id { get; set; }
        public int Level { get; set; }
        public System.DateTime StartDate { get; set; }
        public int CreaterId { get; set; }
        public System.DateTime EndDate { get; set; }
        public bool Enabled { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
        public virtual ICollection<WfwExecutionEvent> WfwExecutionEvents { get; set; }
    }
}
