using System;
using System.Collections.Generic;

namespace DbContextAutoGenerated.Models
{
    public partial class WfwDocumentExecution
    {
        public WfwDocumentExecution()
        {
            this.Documents = new List<Document>();
            this.WfwDocumentWorkSchemes = new List<WfwDocumentWorkScheme>();
        }

        public int Id { get; set; }
        public int Level { get; set; }
        public System.DateTimeOffset StartDate { get; set; }
        public string CreaterSid { get; set; }
        public Nullable<System.DateTimeOffset> EndDate { get; set; }
        public bool Enabled { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
        public virtual ICollection<WfwDocumentWorkScheme> WfwDocumentWorkSchemes { get; set; }
    }
}
