using System;
using System.Collections.Generic;

namespace DbContextAutoGenerated.Models
{
    public partial class WfwDocumentTypesSchem
    {
        public int Id { get; set; }
        public int DocumentTypeId { get; set; }
        public int SchemeId { get; set; }
        public bool Enabled { get; set; }
        public virtual DocumentType DocumentType { get; set; }
        public virtual WfwScheme WfwScheme { get; set; }
    }
}
