using System;
using System.Collections.Generic;

namespace DbContextAutoGenerated.Models
{
    public partial class WfwExecutionEvent
    {
        public int Id { get; set; }
        public int WfwDocumentWorkStagesId { get; set; }
        public System.DateTimeOffset Date { get; set; }
        public string CreaterSid { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> AlternateId { get; set; }
        public int ResultId { get; set; }
        public string Comment { get; set; }
        public virtual WfwDocumentWorkStage WfwDocumentWorkStage { get; set; }
        public virtual WfwEventsResult WfwEventsResult { get; set; }
    }
}
