using System;
using System.Collections.Generic;

namespace DbContextAutoGenerated.Models
{
    public partial class WfwEventsResult
    {
        public WfwEventsResult()
        {
            this.WfwDocumentWorkStages = new List<WfwDocumentWorkStage>();
            this.WfwExecutionEvents = new List<WfwExecutionEvent>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool Success { get; set; }
        public bool Enabled { get; set; }
        public virtual ICollection<WfwDocumentWorkStage> WfwDocumentWorkStages { get; set; }
        public virtual ICollection<WfwExecutionEvent> WfwExecutionEvents { get; set; }
    }
}
