using System;
using System.Collections.Generic;

namespace DbContextAutoGenerated.Models
{
    public partial class WfwExecutionEvent
    {
        public int Id { get; set; }
        public int ExecutionId { get; set; }
        public System.DateTime Date { get; set; }
        public int CreaterId { get; set; }
        public int ResultId { get; set; }
        public string Comment { get; set; }
        public bool Enabled { get; set; }
        public virtual employee employee { get; set; }
        public virtual WfwDocumentExecution WfwDocumentExecution { get; set; }
        public virtual WfwEventsResult WfwEventsResult { get; set; }
    }
}
