using System;
using System.Collections.Generic;

namespace DbContextAutoGenerated.Models
{
    public partial class WfwExecutionEvent
    {
        public int Id { get; set; }
        public int WfwDocumentWorkSchemesId { get; set; }
        public System.DateTimeOffset Date { get; set; }
        public string CreaterSid { get; set; }
        public int ResultId { get; set; }
        public string Comment { get; set; }
        public bool Enabled { get; set; }
        public virtual WfwDocumentWorkScheme WfwDocumentWorkScheme { get; set; }
        public virtual WfwEventsResult WfwEventsResult { get; set; }
    }
}
