using System;
using System.Collections.Generic;

namespace DbContextAutoGenerated.Models
{
    public partial class WfwScheme
    {
        public WfwScheme()
        {
            this.DocumentTypes = new List<DocumentType>();
            this.WfwDocumentTypesSchems = new List<WfwDocumentTypesSchem>();
            this.WfwSchemeStages = new List<WfwSchemeStage>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int Action { get; set; }
        public bool ContinueLastStage { get; set; }
        public bool Enabled { get; set; }
        public virtual ICollection<DocumentType> DocumentTypes { get; set; }
        public virtual ICollection<WfwDocumentTypesSchem> WfwDocumentTypesSchems { get; set; }
        public virtual ICollection<WfwSchemeStage> WfwSchemeStages { get; set; }
    }
}
